# Site
repository: github.com/securespider/securespider.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Vincent Pang
title: Penultimate Year CS Undergrad @ NUS
email: vincent_pang@u.nus.edu
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  securespider
instagram_username: vincent_pang12
linkedin_username: vincent-pang-391222234

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile-pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! I am an aspiring software engineer with a passion for building products that make a difference. I am currently a penultimate year CS undergrad at NUS.<br><br>
  I am currently looking for internship opportunities in the summer of 2024. Feel free to reach out to me if you are interested in working together!<br>


# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Tutoradar
        link: https://github.com/tutoradar/frontend
        link_text: Frontend Lead
        quote: >
          Tutor-Student matching service
        description: |
          Implemented an efficient user interface by leveraging Next.js features for server-side rendering and performance optimization. <br>
          Operated cloud technologies to manage databases and secure authentication.

      - layout: left
        border: weak
        title: Tasked
        link: https://github.com/securespider/Tasked
        link_text: Fullstack Mobile Developer
        quote: >
          Android Calendar application
        description: |
          Developed a mobile application to manage tasks and events using Java and Android Studio. <br>
          Implement secure authentication and data storage using Firebase. <br>

      - layout: left
        border: weak
        title: Statistical Arbitrage Platform 
        link_text: Backend Developer
        quote: >
          Analysis of Forex correlation patterns to identify trading opportunities
        description: |
          Adopted statistical tools using Python libraries numpy, pandas, and matplotlib in analyzing Forex correlation patterns. <br>
          Implemented automated trading in Forex to open and close trades based on analysis metrics using MetaTrader5 API.

      - layout: left
        border: weak
        title: Project Green Warriors
        link_text: Team Leader
        quote: >
          Electrical and water conservation project
        description: |
          Analysis of Darul Ihsan Orphanage's electrical data to lower expenses attributed to wastage. <br>
          Developed a step-wise proposal to conserve energy, eg. switching to fluorescent bulbs which potentially saved 14% of total bills. <br>
          Designed and led a 1-day workshop to encourage recycling and energy-saving practices. <br>

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Gradiant International
        sub_title: Digital Intern
        caption: May 2023 - Present
        link: gradiant.com
        quote: >
          Fullstack Web development 
        description: | # this will include new lines to allow paragraphs
          Designed and developed a web application for engineers to manage and monitor their projects.<br>
          Worked with React, FastAPI and Postgres on Docker containers.<br>
          Organised overseas company retreat for 30+ international employees.
      - layout: right
        title: Mindef
        sub_title: Cybersecurity Analyst
        caption: Apr 2020 - Aug 2021
        link: https://www.mindef.gov.sg/oms/discareers/careers/c4-expert-c4x.html
        quote: >
          Cybersecurity and Networks
        description: | # this will include new lines to allow paragraphs
          Conducted vulnerability assessments and penetration tests on MINDEF/SAF networks and systems.<br>
          Managed and maintained the security of MINDEF/SAF networks and systems.<br>
          Led a team of 4 in 24hr network monitoring missions.<br>


  - title: Education
    layout: list
    content:
      - layout: top-right
        title: National University of Singapore
        sub_title: Bachelor of Computing (Honours) in Computer Science
        caption: 2021-Present
        quote: >
          CAP 4.4/5.0
        description: |
          Focusing on Networks and Distributed Systems and AI/ML
      - layout: top-right
        title: Hwa Chong Institution
        sub_title: A Levels
        caption: 2018-2019
        quote: >
          PCME - CAP 87.5/90
          
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Web Development
        caption: 70% 
        description: | # this will include new lines to allow paragraphs
          Fullstack experience dealing with Next.js, React, JS/TS and Node.js
      - layout: left
        title: Mobile Development
        caption: 60% 
        description: | # this will include new lines to allow paragraphs
          Developed Android apps using Java and Kotlin<br>
          Experience in React Native
      - layout: left
        title: Databases
        caption: 60% 
        description: | # this will include new lines to allow paragraphs
          Expertise in designing and manipulating SQL (Postgres) and NoSQL databases (Firebase)
      - layout: left
        title: Data Engineering and AI/ML
        caption: 50%
        description: | # this will include new lines to allow paragraphs
          Proficient with data manipulation and analysis using numpy, pandas and scikit-learn <br>
          Data visualization with matplotlib and matlab
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
        I stay in Raffles Hall and participate in all kinds of sports and activities.<br>
        I love playing softball and represent my hall in the inter-hall games.<br>
        ![softball](/images/softball.jpg "Softball")
  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
